name: Build and Deploy
on: push

jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   token: ${{ secrets.GITHUB_TOKEN }}

      # Git configure
      - name: Setup git configs
        run: |
          git checkout main
          git config --global user.name "emon526"
          git config --global user.email "emonats526@gmail.com"

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src # The folder the action should deploy.

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_CDFED }}
          channelId: live
          projectId: portfolio-cdfed
        # uses: w9jds/firebase-action@master
        # with:
        #   args: deploy --only hosting:portfolio-cdfed # ID of project at firebase
        # env:
        #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        #   PROJECT_PATH: ./
